#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

info()  { echo -e "${BOLD}$1${NC}"; }
ok()    { echo -e "${GREEN}✓ $1${NC}"; }
warn()  { echo -e "${YELLOW}! $1${NC}"; }
fail()  { echo -e "${RED}✗ $1${NC}"; }

generate_secret() {
    if command -v openssl &>/dev/null; then
        openssl rand -hex 32
    elif [ -r /dev/urandom ]; then
        od -An -tx1 -N32 /dev/urandom | tr -d ' \n'
    else
        fail "Cannot generate secrets. Install openssl."
        exit 1
    fi
}

short_secret() { generate_secret | head -c 16; }

# ── Prerequisites ────────────────────────────────────────────────────

check_prereqs() {
    info "Checking prerequisites..."

    if ! command -v docker &>/dev/null; then
        fail "Docker not found. Install Docker Engine first: https://docs.docker.com/engine/install/"
        exit 1
    fi
    ok "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+' | head -1)"

    if ! docker compose version &>/dev/null; then
        fail "Docker Compose v2 not found. Install the compose plugin: https://docs.docker.com/compose/install/"
        exit 1
    fi
    ok "Docker Compose $(docker compose version --short 2>/dev/null || echo '(version unknown)')"

    if ! docker info &>/dev/null 2>&1; then
        fail "Docker daemon is not running. Start Docker and try again."
        exit 1
    fi
    ok "Docker daemon is running"
}

# ── GPU Detection ────────────────────────────────────────────────────

detect_gpu() {
    info "Checking for NVIDIA GPU..."

    if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null 2>&1; then
        local gpu_name
        gpu_name=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1)
        ok "NVIDIA GPU detected: ${gpu_name:-unknown}"
        echo ""
        read -rp "Enable GPU passthrough for Ollama? (y/N) " confirm
        if [[ "$confirm" =~ ^[Yy]$ ]]; then
            cat > docker-compose.override.yml <<'EOF'
services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
EOF
            ok "Created docker-compose.override.yml with GPU passthrough"
        else
            echo "  Skipping GPU passthrough (CPU-only mode)."
        fi
    else
        echo "  No NVIDIA GPU detected — Ollama will run in CPU-only mode."
    fi
}

# ── Timezone ─────────────────────────────────────────────────────────

detect_timezone() {
    local tz=""

    if [ -f /etc/timezone ]; then
        tz=$(cat /etc/timezone)
    elif command -v timedatectl &>/dev/null; then
        tz=$(timedatectl show --value -p Timezone 2>/dev/null || true)
    elif [ -n "${TZ:-}" ]; then
        tz="$TZ"
    fi

    if [ -n "$tz" ]; then
        read -rp "Detected timezone: $tz — use this? (Y/n) " confirm
        if [[ ! "$confirm" =~ ^[Nn]$ ]]; then
            echo "$tz"
            return
        fi
    fi

    read -rp "Enter timezone (IANA format, e.g. America/Chicago): " tz
    echo "$tz"
}

# ── .env Generation ──────────────────────────────────────────────────

generate_env() {
    info "Setting up .env..."

    if [ -f .env ]; then
        warn ".env already exists."
        read -rp "Overwrite with fresh secrets? (y/N) " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            ok "Keeping existing .env"
            return
        fi
        cp .env ".env.backup.$(date +%s)"
        ok "Backed up existing .env"
    fi

    echo ""
    local tz
    tz=$(detect_timezone)
    echo ""

    info "Generating secrets..."

    cat > .env <<EOF
# Generated by setup.sh — $(date -Iseconds 2>/dev/null || date)

# ── Credentials (auto-generated) ─────────────────────────────────────
N8N_USER=admin
N8N_PASSWORD=$(short_secret)
WEBUI_SECRET_KEY=$(generate_secret)
JWT_SECRET=$(generate_secret)
INTERNAL_API_KEY=$(generate_secret)
VAULTWARDEN_ADMIN_TOKEN=$(generate_secret)

# ── Optional ─────────────────────────────────────────────────────────
API_TOKEN=
SEQ_API_KEY=
SEQ_ADMIN_PASSWORD=$(short_secret)
PORT=8000
VAULTWARDEN_SIGNUPS_ALLOWED=true
TIMEZONE=$tz
EOF

    ok ".env generated with fresh secrets"
}

# ── Validation ───────────────────────────────────────────────────────

validate() {
    info "Validating compose configuration..."

    if docker compose config --quiet 2>/dev/null; then
        ok "docker-compose.yml + .env are valid"
    else
        fail "Validation failed. Run 'docker compose config' to see errors."
        exit 1
    fi
}

# ── Main ─────────────────────────────────────────────────────────────

main() {
    echo ""
    echo -e "${BOLD}═══════════════════════════════════════${NC}"
    echo -e "${BOLD}  nich-neuron setup${NC}"
    echo -e "${BOLD}═══════════════════════════════════════${NC}"
    echo ""

    check_prereqs
    echo ""
    detect_gpu
    echo ""
    generate_env
    echo ""
    validate

    echo ""
    echo -e "${GREEN}${BOLD}Setup complete!${NC} Start the stack with:"
    echo ""
    echo "  docker compose up -d"
    echo ""
    echo "Then visit:"
    echo "  Open WebUI   → http://localhost:3000"
    echo "  n8n          → http://localhost:5678"
    echo "  Dashboard    → http://localhost:9000"
    echo "  Seq logs     → http://localhost:5380"
    echo "  Ntfy         → http://localhost:8090"
    echo "  Uptime Kuma  → http://localhost:3001"
    echo "  Vaultwarden  → http://localhost:8443"
    echo ""
}

main "$@"
